In [8]:
#data load
import pandas as pd

df=pd.read_excel("C:/Users/Anubhav1Rana/OneDrive/Desktop/data analitycs (project)/sales_raw_500.xlsx")

In [9]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
515      1389 2024-02-12    Vikas  North   Laptop  17924  12145
516      1496 2023-04-24    Kiran  North  Printer  23434  16388
517      1031 2023-02-19    Vikas   East  Printer  58883  43579
518      1317 2023-07-05     Aman  North   Laptop  76781  66865
519      1409 2024-01-16    Pooja  North  Monitor  19969  13586

[520 rows x 7 columns]

In [10]:
#removing duplicate
df=df.drop_duplicates()

In [11]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [13]:
#snakecasing column names
df.columns=df.columns.str.lower()
df

     order_id order_date customer region  product  sales   cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [22]:
#fixing date column

df['order_date']=pd.to_datetime(df['order_date'], errors='coerce')

In [23]:
df=df.dropna(subset=['order_date'])

In [24]:
df

,order_id,order_date,customer,region,product,sales,cost,oder_date,profit,year,month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,2023-01-13,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,2023-10-07,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,2023-11-05,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,2024-02-19,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,2024-01-26,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,2023-10-18,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,2023-04-24,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,2023-06-27,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,2023-05-08,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,2023-10-07,12141,2023,10

In [17]:
#adding column 1.profit,2.year and 3.month

df['profit']=df['sales']-df['cost']
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month

C:\Users\Anubhav1Rana\AppData\Local\Temp\ipykernel_18428\1030447658.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['profit']=df['sales']-df['cost']
C:\Users\Anubhav1Rana\AppData\Local\Temp\ipykernel_18428\1030447658.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year']=df['order_date'].dt.year
C:\Users\Anubhav1Rana\AppData\Local\Temp\ipykernel_18428\1030447658.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month']=df['order_date'].dt.month

In [18]:
df

,order_id,order_date,customer,region,product,sales,cost,oder_date,profit,year,month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,2023-01-13,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,2023-10-07,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,2023-11-05,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,2024-02-19,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,2024-01-26,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,2023-10-18,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,2023-04-24,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,2023-06-27,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,2023-05-08,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,2023-10-07,12141,2023,10

In [25]:
 df=df.drop(columns=['oder_date'])

In [27]:
df

,order_id,order_date,customer,region,product,sales,cost,profit,year,month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [29]:
df.to_csv('sales_cleaned.csv',index=False)

In [30]:
import os

In [31]:
os.getcwd()

'C:\\Users\\Anubhav1Rana'

In [33]:
# creating connection between python and SQL

In [35]:
import pandas as pd
from sqlalchemy import create_engine

In [36]:
pd.read_csv('sales_cleaned.csv')

,order_id,order_date,customer,region,product,sales,cost,profit,year,month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
480,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
481,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [40]:
!pip install pymysql

Collecting pymysql
  Using cached pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Using cached pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

In [41]:
import pymysql

In [42]:
engine = create_engine('mysql+pymysql://root:12345@localhost:3306/salesdb')

In [43]:
df.to_sql(name='sales_data',con=engine,if_exists='replace',index=False)

482

In [ ]:
# the cleaned data is now loaded in sql database now we make visuals using Power Bi.